---
repos:
  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
        name: Black
        language_version: python3.6
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-merge-conflict
      - id: requirements-txt-fixer
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.16
    hooks:
      - id: isort
        name: Sort imports
